# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4ffa6fde1a943507efe9889b2b6cf6f8"
name = "empowered-trade-app"
handle = "empowered-trade-app-6"
application_url = "https://rental-catalogue-offense-rl.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "devloyality.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://rental-catalogue-offense-rl.trycloudflare.com/auth/callback",
  "https://rental-catalogue-offense-rl.trycloudflare.com/auth/shopify/callback",
  "https://rental-catalogue-offense-rl.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
